server:
  port: 8775
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true # 但其他服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1 # 指定自己的ip信息,不指定的话会自己寻找
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: data-one-server
  redis:
    # Redis服务器连接密码（默认为空）
    host: 192.168.2.104
    port: 1111
    jedis:
      pool:
       # 连接池最大连接数（使用负值表示没有限制）
        max-active: 5000
       # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
       # 连接池中的最大空闲连接
        max-idle: 30
       # 连接池中的最小空闲连接
        min-idle: 5
    # 连接超时时间（毫秒）
    timeout: 15000
    #集群
#    cluster:
#      nodes: 127.0.0.1:5001,127.0.0.1:5002,127.0.0.1:5003,127.0.0.1:5004,127.0.0.1:5005,127.0.0.1:5006
  cache:
    type: redis

# Swagger界面内容配置
swagger:
  title: XBoot API接口文档
  description: XBoot Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://blog.exrick.cn
  contact:
    name: Exrick
    url: http://blog.exrick.cn
    email: 1012139570@qq.com
feign:
  hystrix:
    enabled: true
